### ISSUE TITLE
File upload, more font size options

### ISSUE THREAD

**Issue by risingsunomi** [webfashionist/RichText#109]
Hello,

I would like to know if current there is file upload? It just seems to allow you to embed a link to file. Also, I have added CSS for the dropdowns from the toolbar to fit more font sizes. Here is the code I am using but might fork this repo and do a pull request.

```javascript
// added to jquery.richtext.js line 368
var fontSizes = [];
let fstart = 12;
for(let i = 0; i < 20; i++) {
     fontSizes.push(fstart + 2);
     fstart = fstart + 2;
 }
```

Added to richtext css
```css
.richText .richText-toolbar ul li a .richText-dropdown-outer .richText-dropdown {
    max-height: 200px;
    overflow-y: auto;
    overflow-x: hidden;
}
```
