### ISSUE TITLE
Problem Font dropdown

### ISSUE THREAD

**Issue by vsc55** [webfashionist/RichText#99]
Font dropdown is not proper, screen-shot attached : Font give dropdown where the bottom section of the dropdown is hidden behind html characters count panel.
![imagen](https://github.com/webfashionist/RichText/assets/13438676/399d4e23-9250-437f-8b8d-7aee65d4fb26)

**A possible solution to the problem:**
```css
.richText {
	// Solves the problem that the menu stays below the other elements of the web, in this case the save changes button".
	z-index: 1;
}
.richText .richText-toolbar:last-child {
	// Fixes the problem that the bottom panel of the character counter appears above the menu.
	z-index: -1;
}
```
![imagen](https://github.com/webfashionist/RichText/assets/13438676/242e468a-e32e-419b-948e-8344e11b9ba7)
